[project]
name = "kaiju-mapper"
version = "0.1.1"
description = "Mapper with the noise"
readme = "README.md"
authors = [
    { name = "Ethan Rooke", email = "pypi@ethan.roo.ke" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.2",
    "zen-mapper>=0.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hypothesis>=6.115.6",
    "matplotlib>=3.9.2",
    "pytest>=8.3.3",
]
docs = [
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=8.1.3",
    "sphinx-autoapi>=3.3.3",
    "sphinx-gallery>=0.18.0",
    "sphinxcontrib-katex>=0.9.10",
	]
